spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false
    username: root
    password: password

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#JPA Settings
  jpa.hibernate.ddl_auto: create
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "caches"
      base-path: "/productionDashboard"
  endpoint:
    health:
      show-details: always
      
logging:
  level:
   com.uttam.project: DEBUG